
export const CRASH_HANDLE_DEBOUNCE = 100;

export const WHITE_SCREEN_HANDLE_SPACE = 5 * 60 * 1000;

export const CRASH_KEYS = {
  WHITE_SCREEN_TIMES: 'WHITE_SCREEN_TIMES',
  LAST_WHITE_SCREEN_TIME: 'LAST_WHITE_SCREEN_TIME',
}

