/*
 * @Author: Rito.Xiao (rito.xiao@ringcentral.com)
 * @Date: 2019-03-04 19:49:50
 * Copyright © RingCentral. All rights reserved.
 */

enum JOB_KEY {
  FETCH_CLIENT_INFO = 'FETCH_CLIENT_INFO',
  FETCH_ACCOUNT_INFO = 'FETCH_ACCOUNT_INFO',
  FETCH_EXTENSION_INFO = 'FETCH_EXTENSION_INFO',
  FETCH_ROLE_PERMISSIONS = 'FETCH_ROLE_PERMISSIONS',
  FETCH_SPECIAL_NUMBER_RULE = 'FETCH_SPECIAL_NUMBER_RULE',
  FETCH_PHONE_DATA = 'FETCH_PHONE_DATA',
  FETCH_EXTENSION_PHONE_NUMBER_LIST = 'FETCH_EXTENSION_PHONE_NUMBER_LIST',
  FETCH_DIALING_PLAN = 'FETCH_DIALING_PLAN',
  FETCH_RC_ACCOUNT_SERVICE_INFO = 'FETCH_RC_ACCOUNT_SERVICE_INFO',
  FETCH_FORWARDING_NUMBER = 'FETCH_FORWARDING_NUMBER',

  RE_LOGIN_GLIP = 'RE_LOGIN_GLIP',
  // TODO: should refactor job key to support dynamic key
  INDEX_DATA = 'INDEX_DATA',
}

const DailyJobIntervalSeconds: number = 86400;

export { JOB_KEY, DailyJobIntervalSeconds };
