import { GROUP_QUERY_TYPE } from '../constants';

const DEFAULT_CONVERSATION_LIST_LIMITS = {
  [GROUP_QUERY_TYPE.ALL]: 20,
  [GROUP_QUERY_TYPE.TEAM]: 20,
  [GROUP_QUERY_TYPE.GROUP]: 20,
  [GROUP_QUERY_TYPE.FAVORITE]: Infinity,
};

export { DEFAULT_CONVERSATION_LIST_LIMITS };
