/*
 * @Author: kasni.huang (kasni.huang@ringcentral.com)
 * @Date: 2019-03-12 10:33:13
 * Copyright © RingCentral. All rights reserved.
 */
enum SYNC_CONFIG_KEYS {
  INDEX_SOCKET_SERVER_HOST = 'INDEX_SOCKET_SERVER_HOST',
  RECONNECT_SOCKET_SERVER_HOST = 'RECONNECT_SOCKET_SERVER_HOST',
  LAST_INDEX_TIMESTAMP = 'LAST_INDEX_TIMESTAMP',
  CAN_UPDATE_INDEX_TIME_STAMP = 'CAN_UPDATE_INDEX_TIME_STAMP',
  FETCHED_REMAINING = 'FETCHED_REMAINING',
  INDEX_SUCCEED = 'INDEX_SUCCEED',
}

const CONFIG_KEYS = {
  SOCKET_SERVER_HOST: 'SOCKET_SERVER_HOST',
  STATIC_HTTP_SERVER: 'STATIC_HTTP_SERVER',
};

export { SYNC_CONFIG_KEYS, CONFIG_KEYS };
