import {
  PersonService,
  ItemService,
  CompanyService,
  GroupService,
  PostService,
  PresenceService,
  StateService,
  ProfileService,
  ENTITY,
} from 'sdk/service';

import * as sdk from 'sdk';

enum ENTITY_NAME  {
  'GROUP'= 'group',
  'PERSON'= 'person',
  'GROUP_STATE'= 'groupState',
  'MY_STATE'= 'myState',
  'ITEM' = 'item',
  'POST'= 'post',
  'PRESENCE'= 'presence',
  'COMPANY'= 'company',
  'PROFILE'= 'profile',
  'POST_SENT_STATUS'= 'postSendStatus',
}

console.log(sdk);

const ENTITY_EVENT_NAME = {
  [ENTITY_NAME.GROUP]: [
    ENTITY.FAVORITE_GROUPS,
    ENTITY.TEAM_GROUPS,
    ENTITY.PEOPLE_GROUPS,
  ],
  [ENTITY_NAME.PERSON]: [ENTITY.PERSON],
  [ENTITY_NAME.GROUP_STATE]: [ENTITY.GROUP_STATE],
  [ENTITY_NAME.MY_STATE]: [ENTITY.MY_STATE],
  [ENTITY_NAME.ITEM]: [ENTITY.ITEM],
  [ENTITY_NAME.POST]: [ENTITY.POST],
  [ENTITY_NAME.PRESENCE]: [ENTITY.PRESENCE],
  [ENTITY_NAME.COMPANY]: [ENTITY.COMPANY],
  [ENTITY_NAME.PROFILE]: [ENTITY.PROFILE],
  [ENTITY_NAME.POST_SENT_STATUS]: [ENTITY.POST_SENT_STATUS],
};

const ENTITY_SERVICE = {
  [ENTITY_NAME.GROUP]: () => GroupService.getInstance(),
  [ENTITY_NAME.PERSON]: () => PersonService.getInstance(),
  [ENTITY_NAME.GROUP_STATE]: () => StateService.getInstance(),
  [ENTITY_NAME.MY_STATE]: () => StateService.getInstance(),
  [ENTITY_NAME.ITEM]: () => ItemService.getInstance(),
  [ENTITY_NAME.POST]: () => PostService.getInstance(),
  [ENTITY_NAME.PRESENCE]: () => PresenceService.getInstance(),
  [ENTITY_NAME.COMPANY]: () => CompanyService.getInstance(),
  [ENTITY_NAME.PROFILE]: () => ProfileService.getInstance(),
  [ENTITY_NAME.POST_SENT_STATUS]: [
    () => PostService.getInstance(),
    'getPostSendStatus',
  ],
};

const HANDLER_TYPE = {
  MULTI_ENTITY: 'multiEntity',
  SINGLE_ENTITY: 'singleEntity',
};

const ENTITY_TYPE = {
  [ENTITY_NAME.GROUP]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.PERSON]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.GROUP_STATE]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.MY_STATE]: HANDLER_TYPE.SINGLE_ENTITY,
  [ENTITY_NAME.ITEM]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.POST]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.PRESENCE]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.COMPANY]: HANDLER_TYPE.MULTI_ENTITY,
  [ENTITY_NAME.PROFILE]: HANDLER_TYPE.SINGLE_ENTITY,
  [ENTITY_NAME.POST_SENT_STATUS]: HANDLER_TYPE.MULTI_ENTITY,
};

const ENTITY_CACHE_COUNT = {
  [ENTITY_NAME.GROUP]: 1000,
  [ENTITY_NAME.PERSON]: 1000,
  [ENTITY_NAME.GROUP_STATE]: 1000,
  [ENTITY_NAME.ITEM]: 1000,
  [ENTITY_NAME.POST]: 50,
  [ENTITY_NAME.PRESENCE]: 1000,
  [ENTITY_NAME.COMPANY]: 1000,
};

export {
  ENTITY_NAME,
  ENTITY_SERVICE,
  ENTITY_TYPE,
  HANDLER_TYPE,
  ENTITY_EVENT_NAME,
  ENTITY_CACHE_COUNT,
};
