import { SettingEntityIds } from 'sdk/module/setting/moduleSetting/types';

const MESSAGE_NOTIFICATION_MANAGER = 'MESSAGE_NOTIFICATION_MANAGER';

const MESSAGE_SERVICE = 'MESSAGE_SERVICE';

const MESSAGE_SETTING_SCOPE = Symbol('MessageSetting');

const SETTING_ITEM__NOTIFICATION_NEW_MESSAGES =
  SettingEntityIds.Notification_NewMessages;

export {
  MESSAGE_NOTIFICATION_MANAGER,
  MESSAGE_SERVICE,
  MESSAGE_SETTING_SCOPE,
  SETTING_ITEM__NOTIFICATION_NEW_MESSAGES,
};
