/*
 * @Author: Paynter Chen
 * @Date: 2019-01-04 10:53:28
 * Copyright © RingCentral. All rights reserved.
 */

export const ERROR_CODES_SDK = {
  GENERAL: 'GENERAL_ERROR',
  UNDEFINED: 'UNDEFINED_ERROR',
  // OAUTH
  OAUTH: 'OAUTH',
  OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT',
  // Invalid Parameter
  INVALID_FIELD: 'INVALID_FIELD',
  INVALID_MODEL_ID: 'INVALID_MODEL_ID',
  ALREADY_TAKEN: 'ALREADY_TAKEN',
  // API
  API_CONFIG_ERROR: 'API_CONFIG_ERROR',

  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',

  POST_DEACTIVATED: 'POST_DEACTIVATED',

  ITEM_DEACTIVATED: 'ITEM_DEACTIVATED',

  GROUP_ARCHIVED: 'GROUP_ARCHIVED',
  GROUP_NOT_MEMBER: 'GROUP_NOT_MEMBER',
  GROUP_NO_PERMISSION: 'GROUP_NO_PERMISSION',
  GROUP_DEACTIVATED: 'GROUP_DEACTIVATED',
};
