/*
 * @Author: Lewi Li (lewi.li@ringcentral.com)
 * @Date: 2019-02-21 10:42:16
 * Copyright © RingCentral. All rights reserved.
 */
const CONFIG_KEYS = {
  FETCHED_REMAINING: 'FETCHED_REMAINING',
  LAST_INDEX_TIMESTAMP: 'LAST_INDEX_TIMESTAMP',
  SOCKET_SERVER_HOST: 'SOCKET_SERVER_HOST',
  STATIC_HTTP_SERVER: 'STATIC_HTTP_SERVER',
  ENV: 'ENV',
  DB_SCHEMA_VERSION: 'DB_SCHEMA_VERSION',
  LAST_CLICKED_GROUP: 'LAST_CLICKED_GROUP',
  PRE_INSERT_IDS: 'PRE_INSERT_IDS',
  MY_STATE_ID: 'MY_STATE_ID',
  ACCOUNT_TYPE: 'ACCOUNT_TYPE',
  PHONE_DATA: 'PHONE_DATA',
  CAN_UPDATE_INDEX_TIME_STAMP: 'CAN_UPDATE_INDEX_TIME_STAMP',
};

export { CONFIG_KEYS };
