/*
 * @Author: Lewi Li (lewi.li@ringcentral.com)
 * @Date: 2019-03-12 14:49:36
 * Copyright © RingCentral. All rights reserved.
 */

enum ERCServiceFeaturePermission {
  VOIP_CALLING,
  INTERNATIONAL_CALLING,
  ON_DEMAND_CALL_RECORDING,
  CALL_PARK,
  CALL_TRANSFER,
  CALL_FLIP,
  BUSINESS_SMS,
  SMS_SEND,
  SMS_RECEIVE,
  PAGER_SEND,
  PAGER_RECEIVING,
  CONFERENCING,
  VIDEO_CONFERENCING,
  READ_BLOCKED_PHONE_NUMBER,
  EDIT_BLOCKED_PHONE_NUMBER,
  READ_COMPANY_CALLLOG,
  FAX,
  FAX_RECEIVE,
  EXTENSION_SETTINGS,
  VOICE_MAIL_TRANSCRIPTION,
  RINGOUT_CALL,
  INTERNAL_CALLS,
  DOMESTIC_CALLS,
  SINGLE_EXTENSION_UI,
  RINGCENTRAL_MOBILE_APP,
  PHONE_SYSTEM,
  BILLING,
  HISTORICAL_REPORTS,
  LIVE_REPORTS,
  QUALITY_OF_SERVICE,
  EMBEDDED_FLAG,
  DND,
  CALL_SWITCH,
  RC_PRESENCE,
  MOBILE_VOIP_EMERGENCY_CALLING,
}

enum PermissionId {
  INTERNAL_CALLS = 'InternalCalls',
  DOMESTIC_CALLS = 'DomesticCalls',
  INTERNATIONAL_CALLS = 'InternationalCalls',
  INTERNATIONAL_CALLING = 'InternationalCalling',
  READ_COMPANY_CALLLOG = 'ReadCompanyCallLog',
  INTERNAL_SMS = 'InternalSMS',
  PERMISSION_MEEINGS = 'Meetings',
}

enum RCServiceFeatureName {
  VOIP_CALLING = 'VoipCalling',
  INTERNATIONAL_CALLING = 'InternationalCalling',
  CALL_PARK = 'CallPark',
  SINGLE_EXTENSION_UI = 'SingleExtensionUI',
  CALL_SWITCH = 'CallSwitch',
  PAGER = 'Pager',
  FAX = 'Fax',
  VIDEO_CONFERENCING = 'VideoConferencing',
}

enum ERCWebSettingUri {
  BILLING_URI,
  PHONE_SYSTEM_URI,
  EXTENSION_URI,
  ANALYTIC_PORTAL_URI,
}

export {
  RCServiceFeatureName,
  PermissionId,
  ERCServiceFeaturePermission,
  ERCWebSettingUri,
};
