export const TELEPHONY_SERVICE = 'TELEPHONY_SERVICE';
export const ANONYMOUS = 'anonymous';
export enum CALL_ACTION {
  FORWARD,
  PARK,
  REPLY,
  FLIP,
}
export const CONTACT_SEARCH_PHONE_NUMBER_ID =
  'TELEPHONY-CONTACT_SEARCH_PHONE_NUMBER_ID-0';
