export const ringOptionTransformer = {
  '0': 'Off',
  'PhoneRing.wav': 'Phone Ring',
  'air-raid-ring.wav': 'Air Raid',
  'allusive-ring.wav': 'Allusive',
  'attention-ring.wav': 'Attention',
  'blub-blub-ring.wav': 'Blub Blub',
  'buzzy-ring.wav': 'Buzzy',
  'communication-channel-ring.wav': 'Channel Open',
  'disco-ring.wav': 'Disco',
  'door-bell-ring.wav': 'Door Bell',
  'fab-ring.wav': 'Fairy',
  'fast-bells-ring.wav': 'Fast Bells',
  'high-gong-ring.wav': 'High Gong',
  'indeed-ring.wav': 'Indeed',
  'nice-ring.wav': 'Nice',
  'ringing-bells-ring.wav': 'Ringing Bells',
  'ring-ring.wav': 'Ring',
  'simple-ring.wav': 'Simple',
  'soothing-ring.wav': 'Soothing',
};
