/*
 * @Author: isaac.liu
 * @Date: 2019-04-02 14:10:17
 * Copyright © RingCentral. All rights reserved.
 */
const SHADOW_HEIGHT = 24;
const ITEM_HEIGHT = 48;
const MAX_ITEM_NUMBER = 5.5;
const MAX_HEIGHT = MAX_ITEM_NUMBER * ITEM_HEIGHT;
const MIN_HEIGHT = ITEM_HEIGHT;
const FULLSCREEN_WIDTH = 640;
const HORIZONTAL_LINE = 1;

const COUNT_TO_SHOW_SEARCH = 10;
const SEARCH_HEIGHT = 98;
const PROFILE_TITLE_HEIGHT = 52;
const DIALOG_MARGIN = 48;
const PROFILE_FIX_HEIGHT = PROFILE_TITLE_HEIGHT + HORIZONTAL_LINE * 2;
const EMPTY_HEIGHT = 270;

export {
  ITEM_HEIGHT,
  MAX_HEIGHT,
  MIN_HEIGHT,
  FULLSCREEN_WIDTH,
  COUNT_TO_SHOW_SEARCH,
  SEARCH_HEIGHT,
  PROFILE_FIX_HEIGHT,
  DIALOG_MARGIN,
  SHADOW_HEIGHT,
  EMPTY_HEIGHT,
};
