enum ENTITY_NAME {
  'GROUP' = 'group',
  'PERSON' = 'person',
  'GROUP_STATE' = 'groupState',
  'MY_STATE' = 'myState',
  'ITEM' = 'item',
  'POST' = 'post',
  'PRESENCE' = 'presence',
  'COMPANY' = 'company',
  'PROFILE' = 'profile',
  'POST_SENT_STATUS' = 'postSendStatus',
  'GLOBAL' = 'global',
}

enum HANDLER_TYPE {
  MULTI_ENTITY,
  SINGLE_ENTITY,
}

enum GLOBAL_KEYS {
  WINDOW_FOCUS = 'WINDOW_FOCUS',
  NETWORK = 'NETWORK',
  IS_SHOW_CREATE_TEAM_DIALOG = 'IS_SHOW_CREATE_TEAM_DIALOG',
  IS_LEFT_NAV_OPEN = 'IS_LEFT_NAV_OPEN',
  CURRENT_USER_ID = 'CURRENT_USER_ID',
  CURRENT_CONVERSATION_ID = 'CURRENT_CONVERSATION_ID',
  APP_SHOW_GLOBAL_LOADING = 'APP_SHOW_GLOBAL_LOADING',
  APP_UMI = 'APP_UMI',
  GROUP_QUERY_TYPE_GROUP_IDS = 'GROUP_QUERY_TYPE_GROUP_IDS',
  GROUP_QUERY_TYPE_TEAM_IDS = 'GROUP_QUERY_TYPE_TEAM_IDS',
  GROUP_QUERY_TYPE_FAVORITE_IDS = 'GROUP_QUERY_TYPE_FAVORITE_IDS',
  UNREAD_TOGGLE_ON = 'UNREAD_TOGGLE_ON',
}

export { ENTITY_NAME, HANDLER_TYPE, GLOBAL_KEYS };
