enum ENTITY_NAME {
  'GROUP' = 'group',
  'GROUP_CONFIG' = 'groupConfig',
  'PERSON' = 'person',
  'GROUP_STATE' = 'groupState',
  'MY_STATE' = 'myState',
  'ITEM' = 'item',
  'POST' = 'post',
  'DISCONTINUOUS_POST' = 'discontinuousPost',
  'PRESENCE' = 'presence',
  'COMPANY' = 'company',
  'PROFILE' = 'profile',
  'GLOBAL' = 'global',
  'PROGRESS' = 'progress',
  'USER_PERMISSION' = 'userPermission',
}

enum HANDLER_TYPE {
  MULTI_ENTITY,
  SINGLE_ENTITY,
}

enum GLOBAL_KEYS {
  ELECTRON_VERSION = 'ELECTRON_VERSION',
  ELECTRON_APP_VERSION = 'ELECTRON_APP_VERSION',
  IS_SHOW_ABOUT_DIALOG = 'IS_SHOW_ABOUT_DIALOG',
  WINDOW_FOCUS = 'WINDOW_FOCUS',
  NETWORK = 'NETWORK',
  IS_LEFT_NAV_OPEN = 'IS_LEFT_NAV_OPEN',
  CURRENT_USER_ID = 'CURRENT_USER_ID',
  CURRENT_COMPANY_ID = 'CURRENT_COMPANY_ID',
  STATIC_HTTP_SERVER = 'STATIC_HTTP_SERVER',
  CURRENT_CONVERSATION_ID = 'CURRENT_CONVERSATION_ID',
  GROUP_QUERY_TYPE_GROUP_IDS = 'GROUP_QUERY_TYPE_GROUP_IDS',
  GROUP_QUERY_TYPE_TEAM_IDS = 'GROUP_QUERY_TYPE_TEAM_IDS',
  GROUP_QUERY_TYPE_FAVORITE_IDS = 'GROUP_QUERY_TYPE_FAVORITE_IDS',
  UNREAD_TOGGLE_ON = 'UNREAD_TOGGLE_ON',
  SHOULD_SHOW_UMI = 'SHOULD_SHOW_UMI',
  JUMP_TO_POST_ID = 'JUMP_TO_POST_ID',
  IS_SHOW_MEMBER_LIST_HEADER_SHADOW = 'IS_SHOW_MEMBER_LIST_HEADER_SHADOW',
  CURRENT_POST_LIST_TYPE = 'CURRENT_POST_LIST_TYPE',
  IN_EDIT_MODE_POST_IDS = 'IN_EDIT_MODE_POST_IDS',
  TOTAL_UNREAD = 'TOTAL_UNREAD',
  FAVORITE_UNREAD = 'FAVORITE_UNREAD',
  DIRECT_MESSAGE_UNREAD = 'DIRECT_MESSAGE_UNREAD',
  TEAM_UNREAD = 'TEAM_UNREAD',
}

export { ENTITY_NAME, HANDLER_TYPE, GLOBAL_KEYS };
