/*
 * @Author: Paynter Chen
 * @Date: 2019-01-04 10:53:33
 * Copyright © RingCentral. All rights reserved.
 */

export const ERROR_CODES_SERVER = {
  GENERAL: 'GENERAL',
  INVALID_GRANT: 'INVALID_GRANT',
  ALREADY_TAKEN: 'ALREADY_TAKEN',
  INVALID_FIELD: 'INVALID_FIELD',
  SYNTAX_ERROR: 'SYNTAX_ERROR',
  URI_ERROR: 'URI_ERROR',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  DELETED: 'DELETED',
  SERVER_ERROR: 'SERVER_ERROR',
};
